services:
  discord-nadeshot-bot-dev:
    entrypoint: ./watcher-docker
    container_name: "discord-nadeshot-bot-dev"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    restart: unless-stopped
